### ISSUE TITLE
#14 Thiết kế trang homepage cho client

### ISSUE THREAD

**Issue by TheVuDoan** [phantranggg/ITSS-Mongu#14]
https://themehunt.com/item/1524993-eshopper-best-free-ecommerce-html-template?_ga=2.134598003.366408514.1572399817-2025920523.1572399817&fbclid=IwAR3m_DkAgVCmqkRfaDwGFaOGghIxBoCuh_Jft1cQywJPMcbN--IJxVKjuIs

**Comment by tungts1101** [comment]
- Chuyển nút login thành nút logout với user đã đăng nhập
- Dẫn link login tới route users/sign_in
- Thêm nút sign_up tới routes users/sign_up
