### ISSUE TITLE
Redesign database

### ISSUE THREAD

**Issue by tungts1101** [phantranggg/ITSS-Mongu#40]
Để đáp ứng yêu cầu query riêng cho 2 loại đồ nam và nữ, cần thiết kế lại database. Cụ thể:
- Tách trường size và quantity trong bảng Product ra thành 1 bảng riêng. Mỗi bản ghi trong bảng Product chỉ còn các trường:
  + id
  + name
  + category_id
  + description
- Sử dụng 1 bảng phụ tên là ProductFeature bao gồm các trường:
  + id
  + size
  + color
  + quantity
  + product_id
  + price
  + gender
- Thay đổi bảng OrderDetail (thay product_id bằng product_feature_id):
  + order_id
  + product_feature_id
  + quantity

**Comment by TheVuDoan** [comment]
@tungts1101 

price để bảng nào hở ô

**Comment by TheVuDoan** [comment]
@tungts1101 

Hiện tại images đang lưu tn nhỉ? nhiều ảnh lưu cùng 1 trường à? có cần tách bảng nữa không?

**Comment by tungts1101** [comment]
> hở

nếu tất cả sản phẩm (khác size/màu) đều chung 1 giá thì để trong Product, không thì để ở ProductFeature. Tôi nghĩ là để trong PF thì hợp lý hơn.

**Comment by tungts1101** [comment]
> @tungts1101
> 
> Hiện tại images đang lưu tn nhỉ? nhiều ảnh lưu cùng 1 trường à? có cần tách bảng nữa không?

image thì mình sử dụng gem carrierwave nên không cần để ý tới relation giữa các bảng, gem sẽ tự động kết nối để mình có thể liên kết 1 product với nhiều ảnh

**Comment by TheVuDoan** [comment]
@tungts1101 

> Tôi nghĩ là để trong PF thì hợp lý hơn

Cũng đc. Thế thì chắc PF nên thêm 1 trường nữa (active, default, ... tên gì đó hợp lí) đánh dấu màu và size mặc định. Ở client khi get dữ liệu thì chọn record có trường này = 1 để hiển thị dữ liệu

**Comment by tungts1101** [comment]
> @tungts1101
> 
> > Tôi nghĩ là để trong PF thì hợp lý hơn
> 
> Cũng đc. Thế thì chắc PF nên thêm 1 trường nữa (active, default, ... tên gì đó hợp lí) đánh dấu màu và size mặc định. Ở client khi get dữ liệu thì chọn record có trường này = 1 để hiển thị dữ liệu

cho hiển thị bằng giá trị đầu tiên query về thì không cần phải thêm trường nữa làm gì

**Comment by TheVuDoan** [comment]
@tungts1101 

1 cái nữa.
Bảng order hiện tại đang lưu product id và quanity
Cái này chắc cũng phải đổi đúng không?
Chuyển productid thành product_feature_id_1 và 2, quantity cũng thế.
OKでしょうか。 :))

**Comment by tungts1101** [comment]
> @tungts1101
> 
> 1 cái nữa.
> Bảng order hiện tại đang lưu product id và quanity
> Cái này chắc cũng phải đổi đúng không?
> Chuyển productid thành product_feature_id_1 và 2, quantity cũng thế.
> OKでしょうか。 :))

Bảng order để lưu hóa đơn từng lần mua bán đúng không nhỉ? Thế làm sao để biết những mặt hàng nào được mua trong cùng 1 lần thế?

**Comment by TheVuDoan** [comment]
@tungts1101  

Khi người dùng thanh toán xong thì lưu các item trong cart vào bảng order đúng không nhỉ? Nhưng vì PF có quantity và price riêng nên trong order phải lưu PF chứ ko phải product

**Comment by TheVuDoan** [comment]
@tungts1101 

Thêm 1 cái nữa, có cần bảng ProductCouple (hoặc tên gì đó hợp lí hơn) lưu các cặp product không?
ProductCouple gồm các trường:
- id
- product_id_1
- product_id_2

**Comment by tungts1101** [comment]
> @tungts1101
> 
> Khi người dùng thanh toán xong thì lưu các item trong cart vào bảng order đúng không nhỉ? Nhưng vì PF có quantity và price riêng nên trong order phải lưu PF chứ ko phải product

Uhm đúng rồi, vì bây giờ các thuộc tính nằm trong PF nên mình sẽ lưu bằng PF_id. Nhưng mà bảng Order đang có những trường gì thế?

**Comment by TheVuDoan** [comment]
@tungts1101 
```ruby
create_table "orders", force: :cascade do |t|
    t.integer "user_id"
    t.datetime "date"
    t.string "ship_name"
    t.text "ship_address"
    t.boolean "shipped"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_orders_on_user_id"
  end
```

**Comment by TheVuDoan** [comment]
```ruby
create_table "order_details", force: :cascade do |t|
    t.integer "order_id"
    t.integer "product_id"
    t.integer "quantity"
    t.datetime "date"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["order_id"], name: "index_order_details_on_order_id"
    t.index ["product_id"], name: "index_order_details_on_product_id"
  end
```

**Comment by TheVuDoan** [comment]
@tungts1101 

Sửa hết xong edit lại cái comment đầu tiên nhé

**Comment by tungts1101** [comment]
> @tungts1101
> 
> Sửa hết xong edit lại cái comment đầu tiên nhé

check lại nhé

**Comment by TheVuDoan** [comment]
@tungts1101 

Thiếu bảng ProductCouple nữa

**Comment by tungts1101** [comment]
> @tungts1101
> 
> Thiếu bảng ProductCouple nữa

@TheVuDoan 
PC là bảng gì thế?

**Comment by TheVuDoan** [comment]
>Thêm 1 cái nữa, có cần bảng ProductCouple (hoặc tên gì đó hợp lí hơn) lưu các cặp product không?
>ProductCouple gồm các trường:
>- id
>- product_id_1
>- product_id_2

**Comment by TheVuDoan** [comment]
Vì trang chủ mình hiển thị theo cặp, chứ ko phải theo từng product

**Comment by tungts1101** [comment]
> Vì trang chủ mình hiển thị theo cặp, chứ ko phải theo từng product

t nghĩ là thêm gender vào ProductFeature, trang chủ vẫn lấy hình ảnh của sản phẩm đầu tiên được query ra thôi, 1 của nữ, 1 của nam

**Comment by TheVuDoan** [comment]
@tungts1101 

Đâu hợp lí lắm nhỉ, tại không phải 2 cái nào đi với nhau cũng được đâu :)))
Quần áo đôi thì phải có cặp riêng của nó chứ.

Ví dụ:
Áo A (Nam, id=1) đi với Áo B (Nữ, id=2) chứ không đi với Áo C (Nữ, id=3)

Chứ query 1 áo nam 1 áo nữ ra thì tách ra bán cho nhanh :))

**Comment by tungts1101** [comment]
> @tungts1101
> 
> Đâu hợp lí lắm nhỉ, tại không phải 2 cái nào đi với nhau cũng được đâu :)))
> Quần áo đôi thì phải có cặp riêng của nó chứ.
> 
> Ví dụ:
> Áo A (Nam, id=1) đi với Áo B (Nữ, id=2) chứ không đi với Áo C (Nữ, id=3)
> 
> Chứ query 1 áo nam 1 áo nữ ra thì tách ra bán cho nhanh :))

Ý t là nam & nữ cùng chung 1 product_id thôi, như kiểu áo Nike GTX 1300 thì làm 1 loại cho nam & 1 loại cho nữ, và lúc bán thì mình bán theo cặp. Còn nếu muốn bản kiểu kết hợp như vậy cũng được. Xem là như thế nào thì trông hợp lý, vì ông tách thành 1 bảng PC thì bảng product cũng phải thêm 1 thuộc tính là gender nữa để biết được là thuộc loại nào.

**Comment by TheVuDoan** [comment]
@tungts1101  

ok t hiểu ý ô r.
Vậy có vẻ không cần thêm bảng mới cũng được

**Comment by TheVuDoan** [comment]
LGTMです！
