### ISSUE TITLE
Banner không hiển thị

### ISSUE THREAD

**Issue by phantranggg** [phantranggg/ITSS-Mongu#61]
Hiện tại
![Screenshot from 2019-11-19 23-51-26](https://user-images.githubusercontent.com/29938253/69167423-8b7bd500-0b27-11ea-9c8a-c5dad659937b.png)

Mong muốn
![Screenshot from 2019-11-19 23-52-12](https://user-images.githubusercontent.com/29938253/69167475-a0f0ff00-0b27-11ea-9955-bc3bcc8e7eb4.png)

**Comment by TheVuDoan** [comment]
Memo: banner trang product detail

**Comment by phantranggg** [comment]
Banner tất cả các trang :3

**Comment by phantranggg** [comment]
Update: homepage đã hiển thị banner

**Comment by phantranggg** [comment]
![image](https://user-images.githubusercontent.com/29938253/69208741-5010f300-0b87-11ea-822c-9ff9c26f1a1f.png)
Banner trang cart chưa hiển thị
