### ISSUE TITLE
Thêm link vào trong ảnh product, dẫn link đến trang detail

### ISSUE THREAD

**Issue by TheVuDoan** [phantranggg/ITSS-Mongu#68]
![image](https://user-images.githubusercontent.com/27731405/69171102-e1537b80-0b2d-11ea-86ed-fa7fd8953948.png)

Hiện tại có nút view-more, nhưng chỉ để link ở nút này thì UX không tốt

**Comment by lehuyhunghedspi** [comment]
fix issue 69
