### ISSUE TITLE
Sửa backend signup

### ISSUE THREAD

**Issue by TheVuDoan** [phantranggg/ITSS-Mongu#69]
<img width="1266" alt="Screen Shot 2019-11-20 at 10 08 00" src="https://user-images.githubusercontent.com/27731405/69205939-fce67280-0b7d-11ea-8413-7d051ac8dd8c.png">

**Comment by tungts1101** [comment]
Sau khi pull code về chạy:
  rails db:migrate:reset
  rails db:seed
