### ISSUE TITLE
Sửa style ảnh product trang home page

### ISSUE THREAD

**Issue by TheVuDoan** [phantranggg/ITSS-Mongu#79]
<img width="1162" alt="Screen Shot 2019-11-20 at 15 06 15" src="https://user-images.githubusercontent.com/27731405/69220419-83fc1080-0ba7-11ea-89ea-4514b4efedbe.png">

Khi tên khác nhau thì độ cao khác nhau -> button lệch nhau

Mong muốn: fix height để button nằm cùng dòng

**Comment by lehuyhunghedspi** [comment]
fixed
